package com.samir.sms.api.model.subject;

public enum CourseItem {
    FRANCAIS,
    MATHEMATIQUES,
    HISTOIRE_GEOGRAPHIE,
    ENSEIGNEMENT_CIVIQUE,
    LANGUES_VIVANTES,
    SCIENCE_VIE_TERRE,
    PHYSIQUE_CHIMIE,
    TECHNOLOGIE,
    EDUCATION_PHYSIQUE,
    ARTS_PLASTIQUES,
    EDUCATION_MUSICALE

}
